spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validete
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:/db/migration
    schemas: public
    default-schema: public 